name: Build Lakka RPi4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache sources and build state
        uses: actions/cache@v4
        with:
          path: |
            sources
            build.*
          key: ${{ runner.os }}-lakka-${{ hashFiles('packages/**/package.mk') }}
          restore-keys: |
            ${{ runner.os }}-lakka-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc curl gcc g++ git gperf make \
            openjdk-11-jre-headless rsync unzip \
            xfonts-utils xsltproc xz-utils zip \
            cmake \
            wget \
            rdfind \
            libparse-yapp-perl \
            libxml-parser-perl \
            patchutils \
            lzop

      - name: Build Lakka RPi4
        run: |
          PROJECT=RPi DEVICE=RPi4 ARCH=arm make image

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: lakka-rpi4-image
          path: target/*.img*

